import type{ArchitectureDecision,SystemDesignSnapshot,SystemDesignWarning,SystemNodeType}from"./systemDesign";
export interface ArchitectureScore{score:number;coverage:number;connectivity:number;traceability:number;resilience:number;warnings:SystemDesignWarning[];antipatterns:Array<{id:string;severity:"high"|"medium"|"low";message:string;nodeIds:string[]}>;}
export interface ArchitectureDiff{addedNodeIds:string[];removedNodeIds:string[];changedNodeIds:string[];addedEdgeIds:string[];removedEdgeIds:string[];changedEdgeIds:string[];}
export interface TraceCandidate{id:string;artifactType:"feature"|"flow"|"code"|"test";artifactId:string;nodeId:string;confidence:number;reason:string;}
const normalize=(value:string)=>new Set(value.toLowerCase().split(/[^\p{L}\p{N}]+/u).filter(token=>token.length>1));
const similarity=(a:string,b:string)=>{const left=normalize(a),right=normalize(b);const overlap=[...left].filter(token=>right.has(token)).length;return overlap/Math.max(1,Math.min(left.size,right.size));};
export function compareArchitecture(base:SystemDesignSnapshot,current:SystemDesignSnapshot):ArchitectureDiff{const compare=<T extends{id:string}>(before:T[],after:T[])=>{const a=new Map(before.map(item=>[item.id,JSON.stringify(item)])),b=new Map(after.map(item=>[item.id,JSON.stringify(item)]));return{added:[...b.keys()].filter(id=>!a.has(id)),removed:[...a.keys()].filter(id=>!b.has(id)),changed:[...a.keys()].filter(id=>b.has(id)&&a.get(id)!==b.get(id))};};const nodes=compare(base.nodes,current.nodes),edges=compare(base.edges,current.edges);return{addedNodeIds:nodes.added,removedNodeIds:nodes.removed,changedNodeIds:nodes.changed,addedEdgeIds:edges.added,removedEdgeIds:edges.removed,changedEdgeIds:edges.changed};}
export function suggestTraceLinks(snapshot:SystemDesignSnapshot,artifacts:Array<{id:string;type:"feature"|"flow"|"code"|"test";title:string}>):TraceCandidate[]{const result:TraceCandidate[]=[];for(const artifact of artifacts)for(const node of snapshot.nodes){const confidence=similarity(`${node.name} ${node.description} ${node.technology}`,artifact.title);if(confidence>=.34)result.push({id:`${artifact.type}.${artifact.id}.${node.id}`,artifactType:artifact.type,artifactId:artifact.id,nodeId:node.id,confidence,reason:"이름·책임·기술 키워드가 겹칩니다."});}return result.sort((a,b)=>b.confidence-a.confidence).slice(0,100);}
export function evaluateArchitecture(snapshot:SystemDesignSnapshot,warnings:SystemDesignWarning[]):ArchitectureScore{const connected=new Set(snapshot.edges.flatMap(edge=>[edge.source,edge.target]));const featureLinks=new Set(snapshot.nodes.flatMap(node=>node.linkedFeatureIds));const externalEdges=snapshot.edges.filter(edge=>snapshot.nodes.some(node=>node.id===edge.source&&node.type==="external"||node.id===edge.target&&node.type==="external"));const antipatterns:ArchitectureScore["antipatterns"]=[];for(const node of snapshot.nodes){const degree=snapshot.edges.filter(edge=>edge.source===node.id||edge.target===node.id).length;if(degree>=Math.max(7,snapshot.nodes.length*.55))antipatterns.push({id:`god.${node.id}`,severity:"medium",message:`${node.name}에 연결이 과도하게 집중됩니다.`,nodeIds:[node.id]});if(node.type==="service"&&snapshot.edges.filter(edge=>edge.source===node.id&&edge.type!=="event").length>=5)antipatterns.push({id:`sync.${node.id}`,severity:"medium",message:`${node.name}의 동기 호출 분산을 검토해 주세요.`,nodeIds:[node.id]});}const unconsumed=snapshot.nodes.filter(node=>node.type==="queue"&&!snapshot.edges.some(edge=>edge.source===node.id));for(const node of unconsumed)antipatterns.push({id:`queue.${node.id}`,severity:"high",message:`${node.name}에 소비자가 없습니다.`,nodeIds:[node.id]});const connectivity=snapshot.nodes.length?connected.size/snapshot.nodes.length:1;const traceability=snapshot.nodes.length?snapshot.nodes.filter(node=>node.linkedFeatureIds.length||node.linkedUserFlowIds.length).length/snapshot.nodes.length:1;const resilience=externalEdges.length?externalEdges.filter(edge=>edge.errorHandling.trim()).length/externalEdges.length:1;const coverage=Math.min(1,featureLinks.size/Math.max(1,snapshot.nodes.length));const score=Math.round((connectivity*.25+traceability*.3+resilience*.25+coverage*.2)*100-Math.min(25,antipatterns.length*4));return{score:Math.max(0,score),coverage,connectivity,traceability,resilience,warnings,antipatterns};}
export function decisionMarkdown(decision:ArchitectureDecision){return`# ${decision.title}\n\n상태: ${decision.status}\n\n## 문제\n${decision.problem}\n\n## 결정\n${decision.decision}\n\n## 대안\n${decision.alternatives.map(item=>`- ${item}`).join("\n")}\n\n## Trade-offs\n${decision.tradeoffs.map(item=>`- ${item}`).join("\n")}\n`;}
export const NODE_TYPE_HINTS:Record<SystemNodeType,string>={client:"UI browser desktop mobile",service:"api service domain server",database:"database storage repository",cache:"cache redis memory",queue:"queue event message",external:"external provider api",component:"component module",group:"system boundary"};
