import{invoke,isTauri}from"@tauri-apps/api/core";import type{SystemDesignProposal,SystemDesignSnapshot,SystemDesignSource,SystemDesignWorkspace}from"../domain/systemDesign";import{validateSystemDesign}from"../domain/systemDesign";import type{SystemDesignRepository}from"../ports/systemDesignRepository";
const now=()=>new Date().toISOString();
class TauriSystemDesignRepository implements SystemDesignRepository{
 initialize(projectId:string,initialSnapshot:SystemDesignSnapshot){return invoke<SystemDesignWorkspace>("initialize_system_design",{input:{projectId,initialSnapshot,createdAt:now()}});}
 saveRevision(projectId:string,designId:string,snapshot:SystemDesignSnapshot,source:SystemDesignSource){return invoke<SystemDesignWorkspace>("save_system_design_revision",{input:{projectId,designId,snapshot,source,createdAt:now()}});}
 createProposal(projectId:string,designId:string,baseRevisionId:string,proposedSnapshot:SystemDesignSnapshot,summary:string){return invoke<SystemDesignProposal>("create_system_design_proposal",{input:{id:`system-proposal-${crypto.randomUUID()}`,projectId,designId,baseRevisionId,proposedSnapshot,summary,source:"codex",createdAt:now()}});}
 decideProposal(projectId:string,proposalId:string,decision:"accepted"|"rejected",rejectionReason?:string){return invoke<SystemDesignWorkspace>("decide_system_design_proposal",{input:{projectId,proposalId,decision,rejectionReason,decidedAt:now()}});}
}
class BrowserSystemDesignRepository implements SystemDesignRepository{
 private key(projectId:string){return`projectstudio:${projectId}:system-design`;}
 async initialize(projectId:string,initialSnapshot:SystemDesignSnapshot){const current=localStorage.getItem(this.key(projectId));if(current)return JSON.parse(current)as SystemDesignWorkspace;const workspace:SystemDesignWorkspace={designId:`system-design-${projectId}`,projectId,revision:{id:`system-revision-${crypto.randomUUID()}`,designId:`system-design-${projectId}`,projectId,revisionNumber:1,snapshot:initialSnapshot,source:"development_mode",createdAt:now()},proposals:[]};localStorage.setItem(this.key(projectId),JSON.stringify(workspace));return workspace;}
 async saveRevision(projectId:string,designId:string,snapshot:SystemDesignSnapshot,source:SystemDesignSource){const errors=validateSystemDesign(snapshot);if(errors.length)throw new Error(errors[0]);const current=await this.initialize(projectId,snapshot);const next={...current,revision:{id:`system-revision-${crypto.randomUUID()}`,designId,projectId,revisionNumber:current.revision.revisionNumber+1,snapshot,source,createdAt:now()}};localStorage.setItem(this.key(projectId),JSON.stringify(next));return next;}
 async createProposal(projectId:string,designId:string,baseRevisionId:string,proposedSnapshot:SystemDesignSnapshot,summary:string){const current=await this.initialize(projectId,proposedSnapshot);const proposal:SystemDesignProposal={id:`system-proposal-${crypto.randomUUID()}`,projectId,designId,baseRevisionId,proposedSnapshot,summary,source:"codex",status:"pending",createdAt:now()};localStorage.setItem(this.key(projectId),JSON.stringify({...current,proposals:[proposal,...current.proposals]}));return proposal;}
 async decideProposal(projectId:string,proposalId:string,decision:"accepted"|"rejected",rejectionReason?:string){const current=await this.initialize(projectId,{schemaVersion:1,title:"",summary:"",nodes:[],edges:[]});const proposal=current.proposals.find(item=>item.id===proposalId);if(!proposal||proposal.status!=="pending")throw new Error("이미 처리됐거나 존재하지 않는 변경안입니다.");if(decision==="accepted"&&proposal.baseRevisionId!==current.revision.id)throw new Error("변경안 생성 후 원본 설계가 수정되었습니다.");const proposals=current.proposals.map(item=>item.id===proposalId?{...item,status:decision,decidedAt:now(),rejectionReason}as SystemDesignProposal:item);const next=decision==="accepted"?{...current,proposals,revision:{id:`system-revision-${crypto.randomUUID()}`,designId:current.designId,projectId,revisionNumber:current.revision.revisionNumber+1,snapshot:proposal.proposedSnapshot,source:"codex"as const,createdAt:now()}}:{...current,proposals};localStorage.setItem(this.key(projectId),JSON.stringify(next));return next;}
}
export const createSystemDesignRepository=():SystemDesignRepository=>isTauri()?new TauriSystemDesignRepository():new BrowserSystemDesignRepository();
