import { useMemo, useState } from "react";
import { compareArchitecture, evaluateArchitecture, suggestTraceLinks } from "./domain/architectureIntelligence";
import { reviewSystemDesign, type ArchitectureDecision, type RuntimeScenario, type SystemDesignRevision, type SystemDesignSnapshot } from "./domain/systemDesign";

type Artifact = { id: string; title: string };

export function ArchitectureInsightsPanel({ snapshot, revisions, features, flows, onChange }: { snapshot: SystemDesignSnapshot; revisions: SystemDesignRevision[]; features: Artifact[]; flows: Artifact[]; onChange: (next: SystemDesignSnapshot) => void }) {
  const [baseRevision, setBaseRevision] = useState("");
  const score = useMemo(() => evaluateArchitecture(snapshot, reviewSystemDesign(snapshot)), [snapshot]);
  const candidates = useMemo(() => suggestTraceLinks(snapshot, [...features.map(item => ({ ...item, type: "feature" as const })), ...flows.map(item => ({ ...item, type: "flow" as const }))]), [features, flows, snapshot]);
  const base = revisions.find(item => item.id === baseRevision);
  const diff = base ? compareArchitecture(base.snapshot, snapshot) : undefined;
  const changeScenarios = (scenarios: RuntimeScenario[]) => onChange({ ...snapshot, scenarios });
  const changeDecisions = (decisions: ArchitectureDecision[]) => onChange({ ...snapshot, decisions });

  function addScenario() { const scenario: RuntimeScenario = { id: `scenario-${crypto.randomUUID()}`, name: `시나리오 ${(snapshot.scenarios?.length ?? 0) + 1}`, description: "주요 런타임 흐름", kind: "success", userFlowIds: [], edgeIds: snapshot.edges.filter(edge => edge.sequence).sort((a, b) => (a.sequence ?? 0) - (b.sequence ?? 0)).map(edge => edge.id) }; onChange({ ...snapshot, scenarios: [...(snapshot.scenarios ?? []), scenario], activeScenarioId: scenario.id, viewType: "runtime" }); }
  function addDecision() { const decision: ArchitectureDecision = { id: `adr-${crypto.randomUUID()}`, title: `설계 결정 ${(snapshot.decisions?.length ?? 0) + 1}`, status: "proposed", problem: "해결하려는 문제", decision: "선택한 구조와 이유", alternatives: [], tradeoffs: [], qualityAttributes: snapshot.qualityAttributes ?? [], relatedFeatureIds: [], relatedNodeIds: [] }; changeDecisions([...(snapshot.decisions ?? []), decision]); }
  function acceptCandidate(candidate: (typeof candidates)[number]) { onChange({ ...snapshot, nodes: snapshot.nodes.map(node => node.id !== candidate.nodeId ? node : candidate.artifactType === "feature" ? { ...node, linkedFeatureIds: [...new Set([...node.linkedFeatureIds, candidate.artifactId])] } : { ...node, linkedUserFlowIds: [...new Set([...node.linkedUserFlowIds, candidate.artifactId])] }) }); }

  return <section className="architecture-insights">
    <header><h4>Architecture Intelligence</h4><strong>{score.score}점</strong></header>
    <div className="architecture-metrics"><span>연결 {Math.round(score.connectivity * 100)}%</span><span>추적 {Math.round(score.traceability * 100)}%</span><span>복원력 {Math.round(score.resilience * 100)}%</span></div>
    {score.antipatterns.length ? <ul>{score.antipatterns.slice(0, 4).map(item => <li key={item.id}>{item.message}</li>)}</ul> : <p>주요 안티패턴이 감지되지 않았습니다.</p>}
    <label>품질 속성<textarea rows={2} value={(snapshot.qualityAttributes ?? []).join("\n")} onChange={event => onChange({ ...snapshot, qualityAttributes: event.target.value.split("\n").map(value => value.trim()).filter(Boolean) })} /></label>
    <label>설계 제약<textarea rows={2} value={(snapshot.constraints ?? []).join("\n")} onChange={event => onChange({ ...snapshot, constraints: event.target.value.split("\n").map(value => value.trim()).filter(Boolean) })} /></label>
    <div className="architecture-insight-actions"><button className="secondary" onClick={addScenario} type="button">런타임 시나리오 추가</button><button className="secondary" onClick={addDecision} type="button">ADR 초안 추가</button></div>
    <details><summary>C4 계층 편집</summary>{snapshot.nodes.map(node => <label key={node.id}>{node.name}<select value={node.parentId ?? ""} onChange={event => onChange({ ...snapshot, nodes: snapshot.nodes.map(item => item.id === node.id ? { ...item, parentId: event.target.value || undefined } : item) })}><option value="">상위 요소 없음</option>{snapshot.nodes.filter(parent => parent.id !== node.id && (parent.type === "group" || parent.c4Level === "context" || parent.c4Level === "container")).map(parent => <option key={parent.id} value={parent.id}>{parent.name}</option>)}</select></label>)}</details>
    {(snapshot.scenarios ?? []).map(scenario => <article className="architecture-editor" key={scenario.id}><input aria-label="런타임 시나리오 이름" value={scenario.name} onChange={event => changeScenarios((snapshot.scenarios ?? []).map(item => item.id === scenario.id ? { ...item, name: event.target.value } : item))} /><select aria-label="런타임 시나리오 유형" value={scenario.kind} onChange={event => changeScenarios((snapshot.scenarios ?? []).map(item => item.id === scenario.id ? { ...item, kind: event.target.value as RuntimeScenario["kind"] } : item))}><option value="success">정상</option><option value="failure">실패</option><option value="recovery">복구</option></select><button className="secondary" type="button" onClick={() => onChange({ ...snapshot, activeScenarioId: scenario.id, viewType: "runtime" })}>흐름 보기</button></article>)}
    {(snapshot.decisions ?? []).map(decision => <article className="architecture-editor" key={decision.id}><input aria-label="ADR 제목" value={decision.title} onChange={event => changeDecisions((snapshot.decisions ?? []).map(item => item.id === decision.id ? { ...item, title: event.target.value } : item))} /><select aria-label="ADR 상태" value={decision.status} onChange={event => changeDecisions((snapshot.decisions ?? []).map(item => item.id === decision.id ? { ...item, status: event.target.value as ArchitectureDecision["status"] } : item))}><option value="proposed">제안</option><option value="accepted">승인</option><option value="deprecated">폐기</option><option value="superseded">대체됨</option></select><textarea aria-label="ADR 문제" rows={2} value={decision.problem} onChange={event => changeDecisions((snapshot.decisions ?? []).map(item => item.id === decision.id ? { ...item, problem: event.target.value } : item))} /><textarea aria-label="ADR 결정" rows={2} value={decision.decision} onChange={event => changeDecisions((snapshot.decisions ?? []).map(item => item.id === decision.id ? { ...item, decision: event.target.value } : item))} /></article>)}
    <label>리비전 비교<select value={baseRevision} onChange={event => setBaseRevision(event.target.value)}><option value="">기준 리비전 선택</option>{revisions.map(item => <option key={item.id} value={item.id}>REV {item.revisionNumber}</option>)}</select></label>
    {diff && <p>노드 +{diff.addedNodeIds.length} / -{diff.removedNodeIds.length} / 변경 {diff.changedNodeIds.length} · 연결 +{diff.addedEdgeIds.length} / -{diff.removedEdgeIds.length} / 변경 {diff.changedEdgeIds.length}</p>}
    <p>연결 추천 후보 {candidates.length}개</p>{candidates.slice(0, 3).map(item => <article className="trace-candidate" key={item.id}><small>{features.find(feature => feature.id === item.artifactId)?.title ?? flows.find(flow => flow.id === item.artifactId)?.title} → {snapshot.nodes.find(node => node.id === item.nodeId)?.name} ({Math.round(item.confidence * 100)}%)</small><button className="secondary" onClick={() => acceptCandidate(item)} type="button">승인</button></article>)}
  </section>;
}
