import { useEffect, useMemo, useState } from "react";
import { Background, Controls, MarkerType, ReactFlow, type Edge, type Node } from "@xyflow/react";
import { createDataDesignRepository } from "./adapters/dataDesignRepository";
import { DATA_QUALITY_RULES, createDataDesignProposal, createExecutionTasks, createInitialDataDesign, emptyDataset, emptyVariable, reviewDataDesign, type DataDesignProposal, type DataDesignRevision, type DataDesignSnapshot, type DatasetRelationship, type DatasetSpec, type ExecutionTask, type VariableSpec } from "./domain/dataDesign";
import type { ProjectSubtype, ProjectType } from "./domain/project";

interface Props { projectId: string; projectName: string; projectIdea: string; projectType: ProjectType; projectSubtype?: ProjectSubtype }
type View = "datasets" | "relationships" | "tasks" | "proposals";

export function DataDesignPage({ projectId, projectName, projectIdea, projectType, projectSubtype }: Props) {
  const repository = useMemo(() => createDataDesignRepository(), []);
  const [revision, setRevision] = useState<DataDesignRevision>();
  const [snapshot, setSnapshot] = useState<DataDesignSnapshot>();
  const [selectedId, setSelectedId] = useState<string>();
  const [view, setView] = useState<View>("datasets");
  const [message, setMessage] = useState("데이터 설계를 불러오는 중입니다.");
  useEffect(() => { const initialSnapshot = createInitialDataDesign(projectType, projectSubtype, projectName, projectIdea); void repository.initialize(projectId, initialSnapshot).then(value => { setRevision(value); setSnapshot(value.snapshot); setSelectedId(value.snapshot.datasets[0]?.id); setMessage(`리비전 ${value.revisionNumber}을 불러왔습니다.`); }).catch(error => setMessage(error instanceof Error ? error.message : String(error))); }, [projectId, projectIdea, projectName, projectSubtype, projectType, repository]);
  if (!snapshot || !revision) return <section className="data-design-page"><p role="status">{message}</p></section>;
  const selected = snapshot.datasets.find(item => item.id === selectedId);
  const warnings = reviewDataDesign(snapshot);
  const updateDataset = (dataset: DatasetSpec) => setSnapshot({ ...snapshot, datasets: snapshot.datasets.map(item => item.id === dataset.id ? dataset : item) });
  const addDataset = () => { const dataset = emptyDataset(); setSnapshot({ ...snapshot, datasets: [...snapshot.datasets, dataset] }); setSelectedId(dataset.id); setView("datasets"); };
  const deleteDataset = (id: string) => { if (!window.confirm("데이터셋과 연결 관계를 삭제할까요?")) return; const datasets = snapshot.datasets.filter(item => item.id !== id); setSnapshot({ ...snapshot, datasets, relationships: snapshot.relationships.filter(item => item.sourceDatasetId !== id && item.targetDatasetId !== id) }); setSelectedId(datasets[0]?.id); };
  const addRelationship = () => { if (snapshot.datasets.length < 2) { setMessage("관계를 만들려면 데이터셋이 두 개 이상 필요합니다."); return; } const relation: DatasetRelationship = { id: crypto.randomUUID(), sourceDatasetId: snapshot.datasets[0].id, targetDatasetId: snapshot.datasets[1].id, joinKeys: "", joinType: "left", cardinality: "1:N", preserveSourceRows: true, duplicateRisk: "", unmatchedPolicy: "", temporalAlignment: "", spatialMapping: "", unitConversion: "" }; setSnapshot({ ...snapshot, relationships: [...snapshot.relationships, relation] }); setView("relationships"); };
  const save = async () => { try { const value = await repository.save(projectId, revision, snapshot); setRevision(value); setMessage(`리비전 ${value.revisionNumber}으로 저장했습니다.`); } catch (error) { setMessage(error instanceof Error ? error.message : "데이터 설계를 저장하지 못했습니다. 입력 내용은 유지됩니다."); } };
  const generateTasks = () => setSnapshot({ ...snapshot, executionTasks: createExecutionTasks(projectType, projectSubtype, snapshot) });
  const propose = () => setSnapshot({ ...snapshot, proposals: [createDataDesignProposal(snapshot), ...snapshot.proposals] });
  const decide = (proposal: DataDesignProposal, decision: "accepted" | "rejected") => setSnapshot({ ...snapshot, qualityPlan: decision === "accepted" ? [...new Set([...snapshot.qualityPlan, ...proposal.proposedQualityRules])] : snapshot.qualityPlan, proposals: snapshot.proposals.map(item => item.id === proposal.id ? { ...item, status: decision, decidedAt: new Date().toISOString() } : item) });
  return <section className="data-design-page">
    <header className="data-design-header"><div><p className="eyebrow">03 · DATA DESIGN</p><h2>{projectType === "machine_learning" ? "데이터와 타깃을 설계합니다." : "분석 데이터 계약을 설계합니다."}</h2><p role="status">{message}</p></div><button onClick={() => void save()} type="button">새 리비전 저장</button></header>
    <nav className="data-design-tabs" aria-label="데이터 설계 보기">{(["datasets", "relationships", "tasks", "proposals"] as View[]).map(id => <button className={view === id ? "active" : ""} key={id} onClick={() => setView(id)} type="button">{{ datasets: "데이터 명세", relationships: "데이터 관계도", tasks: "실행 작업", proposals: "AI 변경안" }[id]}</button>)}</nav>
    <div className="data-design-layout"><aside className="data-design-list"><button onClick={addDataset} type="button">＋ 데이터셋</button>{snapshot.datasets.map(dataset => <button className={dataset.id === selectedId ? "selected" : ""} key={dataset.id} onClick={() => { setSelectedId(dataset.id); setView("datasets"); }} type="button"><strong>{dataset.name}</strong><small>{dataset.source || "출처 미정"} · 변수 {dataset.variables.length}</small></button>)}<button className="secondary" onClick={addRelationship} type="button">＋ 데이터 관계</button></aside>
      <main>{view === "datasets" && (selected ? <DatasetEditor dataset={selected} onChange={updateDataset} onDelete={() => deleteDataset(selected.id)}/> : <div className="empty-state"><p>데이터셋을 추가해 출처·키·변수 계약을 작성하세요.</p></div>)}
        {view === "relationships" && <RelationshipWorkspace snapshot={snapshot} onChange={setSnapshot} onAdd={addRelationship}/>}
        {view === "tasks" && <TaskWorkspace snapshot={snapshot} onChange={setSnapshot} onGenerate={generateTasks}/>}
        {view === "proposals" && <ProposalWorkspace proposals={snapshot.proposals} onCreate={propose} onDecide={decide}/>}</main>
      <aside className="data-quality-panel"><h3>품질 검토</h3>{warnings.length ? <ul>{warnings.map(item => <li key={item}>{item}</li>)}</ul> : <p className="system-review-ok">현재 경고가 없습니다.</p>}<h4>검증 계획</h4>{DATA_QUALITY_RULES.map(rule => <label key={rule}><input checked={snapshot.qualityPlan.includes(rule)} onChange={() => setSnapshot({ ...snapshot, qualityPlan: snapshot.qualityPlan.includes(rule) ? snapshot.qualityPlan.filter(item => item !== rule) : [...snapshot.qualityPlan, rule] })} type="checkbox"/>{rule}</label>)}</aside>
    </div>
  </section>;
}

function DatasetEditor({ dataset, onChange, onDelete }: { dataset: DatasetSpec; onChange: (value: DatasetSpec) => void; onDelete: () => void }) {
  const field = (key: keyof DatasetSpec, label: string) => <label>{label}<input value={String(dataset[key] ?? "")} onChange={event => onChange({ ...dataset, [key]: event.target.value })}/></label>;
  return <section className="dataset-editor"><div className="variable-heading"><h3>데이터셋 명세</h3><button className="secondary danger" onClick={onDelete} type="button">데이터셋 삭제</button></div><div className="data-field-grid">{field("name", "데이터셋 이름")}{field("domain", "데이터 도메인")}{field("source", "출처")}{field("sourceUrl", "출처 URL·기관")}{field("collectionMethod", "수집 방식")}{field("format", "파일·저장 형식")}{field("storageLocation", "저장 위치")}{field("period", "데이터 기간")}{field("refreshCycle", "갱신 주기")}{field("timeGrain", "시간 단위")}{field("spatialGrain", "공간 단위")}{field("primaryKeys", "주요 키")}{field("expectedVolume", "예상 데이터량")}{field("license", "라이선스")}{field("accessPolicy", "접근 권한·정책")}</div><label>설명<textarea value={dataset.description} onChange={event => onChange({ ...dataset, description: event.target.value })}/></label><div className="data-check-row"><label><input checked={dataset.containsPersonalData} onChange={event => onChange({ ...dataset, containsPersonalData: event.target.checked })} type="checkbox"/>개인정보 포함</label><label><input checked={dataset.containsSensitiveData} onChange={event => onChange({ ...dataset, containsSensitiveData: event.target.checked })} type="checkbox"/>민감정보 포함</label><label><input checked={dataset.isRawMutable} onChange={event => onChange({ ...dataset, isRawMutable: event.target.checked })} type="checkbox"/>원본 수정 계획</label></div><div className="variable-heading"><h3>변수 사전</h3><button onClick={() => onChange({ ...dataset, variables: [...dataset.variables, emptyVariable()] })} type="button">＋ 변수</button></div>{dataset.variables.map(variable => <VariableEditor key={variable.id} variable={variable} onChange={next => onChange({ ...dataset, variables: dataset.variables.map(item => item.id === next.id ? next : item) })} onDelete={() => onChange({ ...dataset, variables: dataset.variables.filter(item => item.id !== variable.id) })}/>)}</section>;
}

function VariableEditor({ variable, onChange, onDelete }: { variable: VariableSpec; onChange: (value: VariableSpec) => void; onDelete: () => void }) {
  return <article className="variable-card"><div className="variable-row"><input aria-label="원본 변수명" onChange={event => onChange({ ...variable, sourceName: event.target.value })} placeholder="원본 변수명" value={variable.sourceName}/><input aria-label="표준 변수명" onChange={event => onChange({ ...variable, standardName: event.target.value })} placeholder="표준 변수명" value={variable.standardName}/><select aria-label="변수 역할" onChange={event => onChange({ ...variable, role: event.target.value as VariableSpec["role"] })} value={variable.role}><option value="input">입력</option><option value="target">타깃</option><option value="identifier">식별자</option><option value="metadata">메타데이터</option></select><input aria-label="데이터 타입" onChange={event => onChange({ ...variable, dataType: event.target.value })} placeholder="타입" value={variable.dataType}/><button aria-label="변수 삭제" className="secondary danger" onClick={onDelete} type="button">삭제</button></div><div className="data-field-grid"><label>설명<input value={variable.description} onChange={event => onChange({ ...variable, description: event.target.value })}/></label><label>단위<input value={variable.unit} onChange={event => onChange({ ...variable, unit: event.target.value })}/></label><label>허용 범위<input value={variable.allowedRange} onChange={event => onChange({ ...variable, allowedRange: event.target.value })}/></label><label>범주 값<input value={variable.categories} onChange={event => onChange({ ...variable, categories: event.target.value })}/></label><label>사용 가능 시점<input value={variable.availableAt} onChange={event => onChange({ ...variable, availableAt: event.target.value })}/></label><label>누수 위험<input value={variable.leakageRisk} onChange={event => onChange({ ...variable, leakageRisk: event.target.value })}/></label><label>파생 방식<input disabled={!variable.isDerived} value={variable.derivation} onChange={event => onChange({ ...variable, derivation: event.target.value })}/></label></div><div className="data-check-row"><label><input checked={variable.allowsMissing} onChange={event => onChange({ ...variable, allowsMissing: event.target.checked })} type="checkbox"/>결측 허용</label><label><input checked={variable.isDerived} onChange={event => onChange({ ...variable, isDerived: event.target.checked })} type="checkbox"/>생성 변수</label><label><input checked={variable.containsPersonalData} onChange={event => onChange({ ...variable, containsPersonalData: event.target.checked })} type="checkbox"/>개인정보</label></div></article>;
}

function RelationshipWorkspace({ snapshot, onChange, onAdd }: { snapshot: DataDesignSnapshot; onChange: (value: DataDesignSnapshot) => void; onAdd: () => void }) {
  const nodes: Node[] = snapshot.datasets.map((dataset, index) => ({ id: dataset.id, position: { x: 60 + (index % 3) * 320, y: 60 + Math.floor(index / 3) * 220 }, data: { label: <div><strong>{dataset.name}</strong><small>{dataset.primaryKeys || "키 미정"} · {dataset.variables.length}개 변수</small></div> }, className: "dataset-flow-node" }));
  const edges: Edge[] = snapshot.relationships.map(relation => ({ id: relation.id, source: relation.sourceDatasetId, target: relation.targetDatasetId, label: `${relation.cardinality} · ${relation.joinKeys || "키 미정"}`, type: "smoothstep", markerEnd: { type: MarkerType.ArrowClosed } }));
  return <section className="relationship-workspace"><div className="variable-heading"><div><h3>데이터 관계도</h3><p>관계 세부 정보는 아래 편집기에서 관리하며 N:N은 자동 경고합니다.</p></div><button onClick={onAdd} type="button">＋ 관계</button></div><div className="data-relation-canvas"><ReactFlow nodes={nodes} edges={edges} nodesDraggable={false} nodesConnectable={false} fitView><Background/><Controls/></ReactFlow></div>{snapshot.relationships.length === 0 && <p className="empty-state">데이터셋 사이의 병합 관계가 없습니다.</p>}{snapshot.relationships.map(relation => <RelationshipEditor datasets={snapshot.datasets} key={relation.id} relation={relation} onChange={next => onChange({ ...snapshot, relationships: snapshot.relationships.map(item => item.id === next.id ? next : item) })} onDelete={() => onChange({ ...snapshot, relationships: snapshot.relationships.filter(item => item.id !== relation.id) })}/>)}</section>;
}

function RelationshipEditor({ datasets, relation, onChange, onDelete }: { datasets: DatasetSpec[]; relation: DatasetRelationship; onChange: (value: DatasetRelationship) => void; onDelete: () => void }) {
  const options = datasets.map(item => <option key={item.id} value={item.id}>{item.name}</option>);
  return <article className="relationship-card"><div className="relationship-row"><select aria-label="기준 데이터셋" value={relation.sourceDatasetId} onChange={event => onChange({ ...relation, sourceDatasetId: event.target.value })}>{options}</select><span>→</span><select aria-label="대상 데이터셋" value={relation.targetDatasetId} onChange={event => onChange({ ...relation, targetDatasetId: event.target.value })}>{options}</select><input aria-label="조인 키" placeholder="조인 키" value={relation.joinKeys} onChange={event => onChange({ ...relation, joinKeys: event.target.value })}/><select aria-label="조인 방식" value={relation.joinType} onChange={event => onChange({ ...relation, joinType: event.target.value as DatasetRelationship["joinType"] })}><option value="inner">inner</option><option value="left">left</option><option value="right">right</option><option value="full">full</option></select><select aria-label="카디널리티" value={relation.cardinality} onChange={event => onChange({ ...relation, cardinality: event.target.value as DatasetRelationship["cardinality"] })}><option>1:1</option><option>1:N</option><option>N:1</option><option>N:N</option></select><button aria-label="관계 삭제" className="secondary danger" onClick={onDelete} type="button">삭제</button></div><div className="data-field-grid"><label>중복 위험<input value={relation.duplicateRisk} onChange={event => onChange({ ...relation, duplicateRisk: event.target.value })}/></label><label>매칭 실패 처리<input value={relation.unmatchedPolicy} onChange={event => onChange({ ...relation, unmatchedPolicy: event.target.value })}/></label><label>시간 정렬<input value={relation.temporalAlignment} onChange={event => onChange({ ...relation, temporalAlignment: event.target.value })}/></label><label>지역 코드 매핑<input value={relation.spatialMapping} onChange={event => onChange({ ...relation, spatialMapping: event.target.value })}/></label><label>단위 변환<input value={relation.unitConversion} onChange={event => onChange({ ...relation, unitConversion: event.target.value })}/></label><label><input checked={relation.preserveSourceRows} onChange={event => onChange({ ...relation, preserveSourceRows: event.target.checked })} type="checkbox"/>기준 행 유지</label></div></article>;
}

function TaskWorkspace({ snapshot, onChange, onGenerate }: { snapshot: DataDesignSnapshot; onChange: (value: DataDesignSnapshot) => void; onGenerate: () => void }) {
  const update = (task: ExecutionTask) => onChange({ ...snapshot, executionTasks: snapshot.executionTasks.map(item => item.id === task.id ? task : item) });
  return <section className="task-workspace"><div className="variable-heading"><div><h3>Codex 실행 작업</h3><p>계획 항목을 입력·출력·완료 조건·코드·테스트가 있는 실행 단위로 변환합니다.</p></div><button onClick={onGenerate} type="button">실행 작업 생성</button></div>{snapshot.executionTasks.length === 0 && <p className="empty-state">데이터 명세를 작성한 뒤 실행 작업을 생성하세요.</p>}{snapshot.executionTasks.map(task => <article className="execution-task-card" key={task.id}><header><strong>{task.id}</strong><select aria-label={`${task.id} 상태`} value={task.status} onChange={event => update({ ...task, status: event.target.value as ExecutionTask["status"] })}>{["planned", "data_pending", "ready", "in_progress", "validated", "blocked", "completed", "drift_detected"].map(status => <option key={status}>{status}</option>)}</select></header><label>제목<input value={task.title} onChange={event => update({ ...task, title: event.target.value })}/></label><label>목적<textarea value={task.purpose} onChange={event => update({ ...task, purpose: event.target.value })}/></label><div className="data-field-grid"><label>입력<input value={task.input} onChange={event => update({ ...task, input: event.target.value })}/></label><label>출력<input value={task.output} onChange={event => update({ ...task, output: event.target.value })}/></label><label>예상 변경 파일<input value={task.expectedFiles.join(", ")} onChange={event => update({ ...task, expectedFiles: split(event.target.value) })}/></label><label>코드 경로<input value={task.codePaths.join(", ")} onChange={event => update({ ...task, codePaths: split(event.target.value) })}/></label><label>테스트 경로<input value={task.testPaths.join(", ")} onChange={event => update({ ...task, testPaths: split(event.target.value) })}/></label><label>검증 명령<input value={task.validationCommands.join(", ")} onChange={event => update({ ...task, validationCommands: split(event.target.value) })}/></label></div><button className="secondary danger" onClick={() => onChange({ ...snapshot, executionTasks: snapshot.executionTasks.filter(item => item.id !== task.id) })} type="button">작업 삭제</button></article>)}</section>;
}

function ProposalWorkspace({ proposals, onCreate, onDecide }: { proposals: DataDesignProposal[]; onCreate: () => void; onDecide: (proposal: DataDesignProposal, decision: "accepted" | "rejected") => void }) {
  return <section><div className="variable-heading"><div><h3>AI 변경안 검토</h3><p>제안은 승인 전까지 원본 품질 계획을 변경하지 않습니다.</p></div><button onClick={onCreate} type="button">품질 변경안 생성</button></div>{proposals.length === 0 && <p className="empty-state">아직 생성된 변경안이 없습니다.</p>}{proposals.map(proposal => <article className="proposal-card" key={proposal.id}><header><strong>{proposal.summary}</strong><span>{proposal.status}</span></header><p>제안 검사: {proposal.proposedQualityRules.join(", ") || "추가 제안 없음"}</p><ul>{proposal.assumptions.map(item => <li key={item}>{item}</li>)}</ul>{proposal.status === "pending" && <div><button onClick={() => onDecide(proposal, "accepted")} type="button">변경안 승인</button><button className="secondary" onClick={() => onDecide(proposal, "rejected")} type="button">변경안 거절</button></div>}</article>)}</section>;
}

const split = (value: string) => value.split(",").map(item => item.trim()).filter(Boolean);
