import { useEffect, useMemo, useState } from "react";
import { createDataDesignRepository } from "./adapters/dataDesignRepository";
import { DATA_QUALITY_RULES, emptyDataset, emptyVariable, reviewDataDesign, type DataDesignRevision, type DataDesignSnapshot, type DatasetRelationship, type DatasetSpec, type VariableSpec } from "./domain/dataDesign";
import type { ProjectType } from "./domain/project";

interface Props { projectId: string; projectType: ProjectType }

export function DataDesignPage({ projectId, projectType }: Props) {
  const repository = useMemo(() => createDataDesignRepository(), []);
  const [revision, setRevision] = useState<DataDesignRevision>(); const [snapshot, setSnapshot] = useState<DataDesignSnapshot>();
  const [selectedId, setSelectedId] = useState<string>(); const [message, setMessage] = useState("데이터 설계를 불러오는 중입니다.");
  useEffect(() => { void repository.initialize(projectId).then(value => { setRevision(value); setSnapshot(value.snapshot); setSelectedId(value.snapshot.datasets[0]?.id); setMessage(`리비전 ${value.revisionNumber}을 불러왔습니다.`); }).catch(error => setMessage(error instanceof Error ? error.message : String(error))); }, [projectId, repository]);
  if (!snapshot || !revision) return <section className="data-design-page"><p role="status">{message}</p></section>;
  const selected = snapshot.datasets.find(item => item.id === selectedId); const warnings = reviewDataDesign(snapshot);
  const updateDataset = (dataset: DatasetSpec) => setSnapshot({ ...snapshot, datasets: snapshot.datasets.map(item => item.id === dataset.id ? dataset : item) });
  const addDataset = () => { const dataset = emptyDataset(); setSnapshot({ ...snapshot, datasets: [...snapshot.datasets, dataset] }); setSelectedId(dataset.id); };
  const addRelationship = () => { if (snapshot.datasets.length < 2) { setMessage("관계를 만들려면 데이터셋이 두 개 이상 필요합니다."); return; } const relation: DatasetRelationship = { id: crypto.randomUUID(), sourceDatasetId: snapshot.datasets[0].id, targetDatasetId: snapshot.datasets[1].id, joinKeys: "", joinType: "left", cardinality: "1:N", preserveSourceRows: true, duplicateRisk: "", unmatchedPolicy: "", temporalAlignment: "", spatialMapping: "", unitConversion: "" }; setSnapshot({ ...snapshot, relationships: [...snapshot.relationships, relation] }); };
  const save = async () => { const value = await repository.save(projectId, revision, snapshot); setRevision(value); setMessage(`리비전 ${value.revisionNumber}으로 저장했습니다.`); };
  return <section className="data-design-page"><header className="data-design-header"><div><p className="eyebrow">03 · DATA DESIGN</p><h2>{projectType === "machine_learning" ? "데이터와 타깃을 설계합니다." : "분석 데이터 계약을 설계합니다."}</h2><p>{message}</p></div><button onClick={() => void save()} type="button">새 리비전 저장</button></header><div className="data-design-layout"><aside className="data-design-list"><button onClick={addDataset} type="button">＋ 데이터셋</button>{snapshot.datasets.map(dataset => <button className={dataset.id === selectedId ? "selected" : ""} key={dataset.id} onClick={() => setSelectedId(dataset.id)} type="button"><strong>{dataset.name}</strong><small>{dataset.source || "출처 미정"} · 변수 {dataset.variables.length}</small></button>)}<button className="secondary" onClick={addRelationship} type="button">＋ 데이터 관계</button></aside><main>{selected ? <DatasetEditor dataset={selected} onChange={updateDataset}/> : <div className="empty-state"><p>데이터셋을 추가해 출처·키·변수 계약을 작성하세요.</p></div>}<section className="data-relationship-section"><h3>데이터 관계</h3>{snapshot.relationships.map(relation => <RelationshipEditor datasets={snapshot.datasets} key={relation.id} relation={relation} onChange={next => setSnapshot({ ...snapshot, relationships: snapshot.relationships.map(item => item.id === next.id ? next : item) })} onDelete={() => setSnapshot({ ...snapshot, relationships: snapshot.relationships.filter(item => item.id !== relation.id) })}/>)}</section></main><aside className="data-quality-panel"><h3>품질 검토</h3>{warnings.length ? <ul>{warnings.map(item => <li key={item}>{item}</li>)}</ul> : <p className="system-review-ok">현재 경고가 없습니다.</p>}<h4>검증 계획</h4>{DATA_QUALITY_RULES.map(rule => <label key={rule}><input checked={snapshot.qualityPlan.includes(rule)} onChange={() => setSnapshot({ ...snapshot, qualityPlan: snapshot.qualityPlan.includes(rule) ? snapshot.qualityPlan.filter(item => item !== rule) : [...snapshot.qualityPlan, rule] })} type="checkbox"/>{rule}</label>)}</aside></div></section>;
}

function DatasetEditor({ dataset, onChange }: { dataset: DatasetSpec; onChange: (value: DatasetSpec) => void }) {
  const field = (key: keyof DatasetSpec, label: string) => <label>{label}<input value={String(dataset[key] ?? "")} onChange={event => onChange({ ...dataset, [key]: event.target.value })}/></label>;
  return <section className="dataset-editor"><h3>데이터셋 명세</h3><div className="data-field-grid">{field("name", "데이터셋 이름")}{field("domain", "데이터 도메인")}{field("source", "출처")}{field("sourceUrl", "출처 URL·기관")}{field("collectionMethod", "수집 방식")}{field("format", "파일·저장 형식")}{field("storageLocation", "저장 위치")}{field("period", "데이터 기간")}{field("refreshCycle", "갱신 주기")}{field("timeGrain", "시간 단위")}{field("spatialGrain", "공간 단위")}{field("primaryKeys", "주요 키")}{field("license", "라이선스")}{field("accessPolicy", "접근 권한·정책")}</div><label>설명<textarea value={dataset.description} onChange={event => onChange({ ...dataset, description: event.target.value })}/></label><div className="data-check-row"><label><input checked={dataset.containsPersonalData} onChange={event => onChange({ ...dataset, containsPersonalData: event.target.checked })} type="checkbox"/>개인정보 포함</label><label><input checked={dataset.containsSensitiveData} onChange={event => onChange({ ...dataset, containsSensitiveData: event.target.checked })} type="checkbox"/>민감정보 포함</label><label><input checked={dataset.isRawMutable} onChange={event => onChange({ ...dataset, isRawMutable: event.target.checked })} type="checkbox"/>원본 수정 계획</label></div><div className="variable-heading"><h3>변수 사전</h3><button onClick={() => onChange({ ...dataset, variables: [...dataset.variables, emptyVariable()] })} type="button">＋ 변수</button></div>{dataset.variables.map(variable => <VariableEditor key={variable.id} variable={variable} onChange={next => onChange({ ...dataset, variables: dataset.variables.map(item => item.id === next.id ? next : item) })} onDelete={() => onChange({ ...dataset, variables: dataset.variables.filter(item => item.id !== variable.id) })}/>)}</section>;
}

function VariableEditor({ variable, onChange, onDelete }: { variable: VariableSpec; onChange: (value: VariableSpec) => void; onDelete: () => void }) { return <article className="variable-row"><input aria-label="원본 변수명" onChange={event => onChange({ ...variable, sourceName: event.target.value })} placeholder="원본 변수명" value={variable.sourceName}/><input aria-label="표준 변수명" onChange={event => onChange({ ...variable, standardName: event.target.value })} placeholder="표준 변수명" value={variable.standardName}/><select aria-label="변수 역할" onChange={event => onChange({ ...variable, role: event.target.value as VariableSpec["role"] })} value={variable.role}><option value="input">입력</option><option value="target">타깃</option><option value="identifier">식별자</option><option value="metadata">메타데이터</option></select><input aria-label="데이터 타입" onChange={event => onChange({ ...variable, dataType: event.target.value })} placeholder="타입" value={variable.dataType}/><input aria-label="사용 가능 시점" onChange={event => onChange({ ...variable, availableAt: event.target.value })} placeholder="사용 가능 시점" value={variable.availableAt}/><button aria-label="변수 삭제" className="secondary danger" onClick={onDelete} type="button">삭제</button></article>; }

function RelationshipEditor({ datasets, relation, onChange, onDelete }: { datasets: DatasetSpec[]; relation: DatasetRelationship; onChange: (value: DatasetRelationship) => void; onDelete: () => void }) { const options = datasets.map(item => <option key={item.id} value={item.id}>{item.name}</option>); return <article className="relationship-row"><select aria-label="기준 데이터셋" value={relation.sourceDatasetId} onChange={event => onChange({ ...relation, sourceDatasetId: event.target.value })}>{options}</select><span>→</span><select aria-label="대상 데이터셋" value={relation.targetDatasetId} onChange={event => onChange({ ...relation, targetDatasetId: event.target.value })}>{options}</select><input aria-label="조인 키" placeholder="조인 키" value={relation.joinKeys} onChange={event => onChange({ ...relation, joinKeys: event.target.value })}/><select aria-label="카디널리티" value={relation.cardinality} onChange={event => onChange({ ...relation, cardinality: event.target.value as DatasetRelationship["cardinality"] })}><option>1:1</option><option>1:N</option><option>N:1</option><option>N:N</option></select><button aria-label="관계 삭제" className="secondary danger" onClick={onDelete} type="button">삭제</button></article>; }
