import { useCallback, useEffect, useMemo, useState, type CSSProperties } from "react";
import { Background, Controls, MarkerType, Panel, type Connection, type Edge, type Node } from "@xyflow/react";
import { createFeatureRepository } from "./adapters/featureRepository";
import { createUserFlowRepository } from "./adapters/userFlowRepository";
import { createDevelopmentFeatureSpec, NODE_COLORS } from "./domain/feature";
import { connectedUserFlowNodeIds, createExecutionPipelineSpec, createUserFlowSpec, isIncompleteGeneratedFlow, isLegacyPipelineNodeId, reconcileUserFlowLanes, summarizeUserFlowCompletion, type UserFlowNode, type UserFlowNodeKind } from "./domain/userFlow";
import { isInterfaceProject, type ProjectSubtype, type ProjectType } from "./domain/project";
import { UserFlowLaneNode, UserFlowNodeCard, type UserFlowNodeData } from "./UserFlowNodeCard";
import { ImmediateReactFlow as ReactFlow } from "./ImmediateReactFlow";

const nodeTypes={userFlow:UserFlowNodeCard,userFlowLane:UserFlowLaneNode};
const FLOW_WORKSPACE_HEIGHT=1080;const SHEET_LANE_HEIGHT=760;const OVERVIEW_LANE_HEIGHT=230;const USER_FLOW_LAYOUT_VERSION="swimlane-columns-v9";
type UserFlowViewMode="sheet"|"overview"|"focus";
interface Props{projectId:string;sourceDocumentId:string;projectName?:string;projectIdea?:string;projectType:ProjectType;projectSubtype?:ProjectSubtype;}
function FlowEditor({node,lanes,nextNodes,onSave,onClose}:{node:UserFlowNode;lanes:import("./domain/userFlow").UserFlowLane[];nextNodes:UserFlowNode[];onSave:(node:UserFlowNode)=>Promise<void>;onClose:()=>void}){
  const[draft,setDraft]=useState(node);const[message,setMessage]=useState<string>();
  async function save(){try{await onSave(draft);setMessage("유저플로우 단계를 저장했습니다.");}catch{setMessage("저장하지 못했습니다. 편집 내용은 유지됩니다.");}}
  async function changeColor(colorKey:UserFlowNode["colorKey"]){const updated={...draft,colorKey};setDraft(updated);setMessage("색상을 저장하는 중…");try{await onSave(updated);setMessage("노드 색상을 자동 저장했습니다.");}catch{setMessage("색상을 저장하지 못했습니다. 선택은 유지됩니다.");}}
  return <aside className="flow-editor"><button className="panel-close" onClick={onClose} type="button">×</button><div><p className="eyebrow">FLOW STEP DETAIL</p><h3>단계 편집</h3><small>ID {draft.id}</small><label className="flow-editor-completion"><input aria-label="흐름 검수 완료" checked={Boolean(draft.isCompleted)} onChange={event=>setDraft({...draft,isCompleted:event.currentTarget.checked})} type="checkbox"/><span>사용 흐름 검수 완료로 표시</span></label><label>단계 이름<input aria-label="단계 이름" value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})}/></label><label>단계 종류<select aria-label="단계 종류" value={draft.kind} onChange={event=>setDraft({...draft,kind:event.target.value as UserFlowNodeKind})}><option value="phase">대단계</option><option value="screen">화면</option><option value="action">행동</option><option value="decision">분기</option><option value="result">결과</option></select></label><label>소속 스윔레인<select aria-label="소속 스윔레인" value={draft.laneId} onChange={event=>setDraft({...draft,laneId:event.target.value})}>{lanes.map(lane=><option key={lane.id} value={lane.id}>{lane.title}</option>)}</select></label><label>분기 조건<input aria-label="분기 조건" placeholder="선택에 따라 경로가 달라질 때만 입력" value={draft.branchCondition??""} onChange={event=>setDraft({...draft,branchCondition:event.target.value})}/></label><label>연결된 기능명세<input aria-label="연결된 기능명세" readOnly value={(draft.linkedFeatureIds??[]).join(", ")||"연결 없음"}/></label><div className="flow-next-nodes"><span>다음 노드</span><p>{nextNodes.length?nextNodes.map(item=>item.title).join(" · "):"연결 없음"}</p></div><div className="node-color-palette" aria-label="노드 색상">{NODE_COLORS.map(color=><button aria-label={`${color.label} 색상`} className={draft.colorKey===color.key?"selected":""} key={color.key} onClick={()=>void changeColor(color.key)} style={{"--node-color":color.color} as CSSProperties} type="button" />)}</div><label>세부 내용<textarea aria-label="단계 세부 내용" rows={6} value={draft.description} onChange={event=>setDraft({...draft,description:event.target.value})}/></label><button onClick={()=>void save()} type="button">변경 저장</button>{message&&<p className="document-save-message">{message}</p>}</div></aside>;
}
export function UserFlowPage({projectId,sourceDocumentId,projectName,projectIdea,projectType,projectSubtype}:Props){
  const featureRepository=useMemo(()=>createFeatureRepository(),[]);const repository=useMemo(()=>createUserFlowRepository(),[]);
  const generatedFeatures=useMemo(()=>createDevelopmentFeatureSpec(projectId,projectName,projectIdea),[projectId,projectName,projectIdea]);
  const[flowNodes,setFlowNodes]=useState<UserFlowNode[]>([]);const[flowEdges,setFlowEdges]=useState<import("./domain/userFlow").UserFlowEdge[]>([]);const[lanes,setLanes]=useState<import("./domain/userFlow").UserFlowLane[]>([]);const[selectedId,setSelectedId]=useState<string>();const[message,setMessage]=useState("유저플로우를 구성하는 중…");
  const[activeNodeId,setActiveNodeId]=useState<string>();const[focusNodeId,setFocusNodeId]=useState<string>();const[viewMode,setViewMode]=useState<UserFlowViewMode>("sheet");const[activeLaneId,setActiveLaneId]=useState<string>();
  useEffect(()=>{const isInterface=isInterfaceProject(projectType);const versionKey=`projectstudio:${projectId}:workflow-layout`;const layoutVersion=`${USER_FLOW_LAYOUT_VERSION}-${projectType}-${projectSubtype??"default"}`;const savedLayoutVersion=localStorage.getItem(versionKey);const shouldReplace=savedLayoutVersion!==null&&savedLayoutVersion!==layoutVersion;void(async()=>{try{const features=await featureRepository.initialize(projectId,sourceDocumentId,generatedFeatures);const generatedLayout=isInterface?createUserFlowSpec(projectId,features):createExecutionPipelineSpec(projectId,features,projectType,projectSubtype);let spec=await repository.initialize(projectId,generatedLayout.nodes,generatedLayout.edges,shouldReplace);const repaired=!isInterface&&isIncompleteGeneratedFlow(spec.nodes,generatedLayout.nodes);if(repaired)spec=await repository.initialize(projectId,generatedLayout.nodes,generatedLayout.edges,true);const legacyIds=!isInterface?spec.nodes.filter(node=>isLegacyPipelineNodeId(node.id)).map(node=>node.id):[];if(legacyIds.length){await Promise.all(legacyIds.map(nodeId=>repository.deleteNode(projectId,nodeId)));const removed=new Set(legacyIds);spec={nodes:spec.nodes.filter(node=>!removed.has(node.id)),edges:spec.edges.filter(edge=>!removed.has(edge.sourceNodeId)&&!removed.has(edge.targetNodeId))};}const mergedNodes=spec.nodes.map(node=>({...generatedLayout.nodes.find(item=>item.id===node.id),...node}));const reconciled=reconcileUserFlowLanes(mergedNodes,generatedLayout.lanes);setLanes(reconciled.lanes);setActiveLaneId(reconciled.lanes[0]?.id);setFlowNodes(reconciled.nodes);setFlowEdges(spec.edges);localStorage.setItem(versionKey,layoutVersion);setMessage(repaired||legacyIds.length?"누락되거나 충돌한 분석 단계를 기본 실행 파이프라인으로 복구했습니다.":shouldReplace?(isInterface?"사용 시나리오별 화면·행동 흐름으로 다시 구성했습니다.":"프로젝트 유형과 세부 유형에 맞는 실행 파이프라인으로 구성했습니다."):(isInterface?"저장된 유저플로우와 노드 위치를 불러왔습니다.":"저장된 실행 파이프라인을 불러왔습니다."));}catch{setMessage(isInterface?"유저플로우를 불러오지 못했습니다.":"실행 파이프라인을 불러오지 못했습니다.");}})();},[featureRepository,generatedFeatures,projectId,projectSubtype,projectType,repository,sourceDocumentId]);
  const focusedIds=useMemo(()=>viewMode==="focus"&&focusNodeId?connectedUserFlowNodeIds(flowEdges,focusNodeId,2):undefined,[flowEdges,focusNodeId,viewMode]);
  const completionSummary=useMemo(()=>summarizeUserFlowCompletion(flowNodes),[flowNodes]);
  const laneCompletion=useMemo(()=>new Map(lanes.map(lane=>[lane.id,summarizeUserFlowCompletion(flowNodes.filter(node=>node.laneId===lane.id))])),[flowNodes,lanes]);
  const visibleFlowNodes=focusedIds?flowNodes.filter(node=>focusedIds.has(node.id)):viewMode==="sheet"?flowNodes.filter(node=>node.laneId===activeLaneId):flowNodes;const visibleLaneIds=new Set(visibleFlowNodes.map(node=>node.laneId));const visibleLanes=viewMode==="overview"?lanes:lanes.filter(lane=>visibleLaneIds.has(lane.id));
  const visibleCompletionSummary=summarizeUserFlowCompletion(visibleFlowNodes);
  const visualLaneHeight=viewMode==="overview"?OVERVIEW_LANE_HEIGHT:viewMode==="sheet"?SHEET_LANE_HEIGHT:Math.min(360,FLOW_WORKSPACE_HEIGHT);
  const workspaceWidth=Math.max(viewMode==="overview"?1920:1480,...visibleFlowNodes.map(node=>node.positionX+500));const laneNodes:Node[] = visibleLanes.map((lane,index)=>({id:`lane-${lane.id}`,type:"userFlowLane",position:{x:0,y:index*visualLaneHeight},data:{title:lane.title,colorKey:lane.colorKey},draggable:false,selectable:false,connectable:false,zIndex:-1,style:{width:workspaceWidth,height:visualLaneHeight}}));
  const contentNodes:Node<UserFlowNodeData>[] = visibleFlowNodes.map(node=>{const lane=lanes.find(item=>item.id===node.laneId);const scale=visualLaneHeight/(lane?.height??visualLaneHeight);const overviewOffset=190;return{id:node.id,type:"userFlow",selected:node.id===activeNodeId,parentId:`lane-${node.laneId}`,extent:"parent",position:{x:node.positionX+overviewOffset,y:(node.positionY-(lane?.positionY??0))*scale},data:{node,onSelect:(item:UserFlowNode)=>{setActiveNodeId(item.id);setSelectedId(item.id);setMessage(`‘${item.title}’ 상세 정보를 표시합니다.`);},onAdd:handleAddNode,onEdit:(item:UserFlowNode)=>setSelectedId(item.id),onDelete:handleDeleteNode,onCompletionChange:handleCompletionChange},zIndex:2,className:viewMode==="overview"?"overview-node":""};});
  const nodes:Node[]=[...laneNodes,...contentNodes];const visibleNodeIds=new Set(visibleFlowNodes.map(node=>node.id));
  const edges:Edge[]=flowEdges.filter(edge=>visibleNodeIds.has(edge.sourceNodeId)&&visibleNodeIds.has(edge.targetNodeId)).map(edge=>({id:edge.id,source:edge.sourceNodeId,target:edge.targetNodeId,type:"smoothstep",pathOptions:{borderRadius:10,offset:28},markerEnd:{type:MarkerType.ArrowClosed,color:"var(--theme-connector)"},style:{stroke:"var(--theme-connector)",strokeWidth:2}}));
  const handleDragStop=useCallback((_:MouseEvent|TouchEvent,node:Node)=>{const current=flowNodes.find(item=>item.id===node.id);if(!current)return;const lane=lanes.find(item=>item.id===current.laneId);const scale=visualLaneHeight/(lane?.height??visualLaneHeight);const updated={...current,positionX:Math.max(0,node.position.x-190),positionY:node.position.y/scale+(lane?.positionY??0)};setFlowNodes(items=>items.map(item=>item.id===updated.id?updated:item));void repository.updateNode(updated).then(()=>setMessage("스윔레인 안의 노드 위치를 저장했습니다.")).catch(()=>setMessage("단계 위치를 저장하지 못했습니다."));},[flowNodes,lanes,repository,visualLaneHeight]);
  async function handleSave(node:UserFlowNode){const saved=await repository.updateNode(node);setFlowNodes(items=>items.map(item=>item.id===saved.id?saved:item));}
  async function handleCompletionChange(node:UserFlowNode,isCompleted:boolean){const updated={...node,isCompleted};try{const saved=await repository.updateNode(updated);setFlowNodes(items=>items.map(item=>item.id===saved.id?saved:item));setMessage(`‘${saved.title}’ 단계를 ${isCompleted?"흐름 검수 완료":"미검수"}로 저장했습니다.`);}catch{setMessage("흐름 검수 상태를 저장하지 못했습니다. 기존 상태를 유지합니다.");}}
  async function handleConnect(connection:Connection){if(!connection.source||!connection.target)return;const source=flowNodes.find(node=>node.id===connection.source);const target=flowNodes.find(node=>node.id===connection.target);const reaches=(from:string,to:string,visited=new Set<string>()):boolean=>{if(from===to)return true;if(visited.has(from))return false;visited.add(from);return flowEdges.filter(edge=>edge.sourceNodeId===from).some(edge=>reaches(edge.targetNodeId,to,visited));};if(!source||!target||source.laneId!==target.laneId){setMessage("같은 스윔레인의 노드끼리만 연결할 수 있습니다.");return;}if(reaches(target.id,source.id)){setMessage("순환 흐름은 만들 수 없습니다.");return;}try{const edge=await repository.connect(projectId,connection.source,connection.target);setFlowEdges(items=>[...items,edge]);setMessage("단계 연결을 저장했습니다.");}catch(error){setMessage(error instanceof Error?error.message:"단계를 연결하지 못했습니다.");}}
  async function handleAddNode(parent:UserFlowNode){const node:UserFlowNode={id:`flow-${crypto.randomUUID()}`,projectId,laneId:parent.laneId,title:"새 사용자 행동",description:"사용자가 현재 화면에서 수행하는 행동과 다음 화면을 작성해 주세요.",kind:"action",positionX:parent.positionX+260,positionY:parent.positionY+72,colorKey:parent.colorKey??"violet",depth:(parent.depth??0)+1,parentId:parent.id,linkedFeatureIds:parent.linkedFeatureIds,isCompleted:false};try{const saved=await repository.createNode(node);const edge=await repository.connect(projectId,parent.id,saved.id);setFlowNodes(items=>[...items,saved]);setFlowEdges(items=>[...items,edge]);setActiveNodeId(saved.id);setSelectedId(saved.id);setMessage("같은 스윔레인에 다음 단계를 추가했습니다.");}catch(error){setMessage(error instanceof Error?error.message:"단계를 추가하지 못했습니다.");}}
  async function handleDeleteNode(node:UserFlowNode){if(!window.confirm(`‘${node.title}’ 단계와 연결선을 삭제할까요?`))return;try{await repository.deleteNode(projectId,node.id);setFlowNodes(items=>items.filter(item=>item.id!==node.id));setFlowEdges(items=>items.filter(edge=>edge.sourceNodeId!==node.id&&edge.targetNodeId!==node.id));setActiveNodeId(undefined);setSelectedId(undefined);setMessage("단계와 연결선을 삭제했습니다.");}catch(error){setMessage(error instanceof Error?error.message:"단계를 삭제하지 못했습니다.");}}
  async function resetLayout(isCompact=false){const features=await featureRepository.initialize(projectId,sourceDocumentId,generatedFeatures);const generated=isInterfaceProject(projectType)?createUserFlowSpec(projectId,features):createExecutionPipelineSpec(projectId,features,projectType,projectSubtype);const positioned=flowNodes.map(node=>{const base=generated.nodes.find(item=>item.id===node.id);if(!base)return node;return{...node,positionX:isCompact?80+(base.positionX-90)*.84:base.positionX,positionY:base.positionY,colorKey:base.colorKey};});const reconciled=reconcileUserFlowLanes(positioned,generated.lanes);setLanes(reconciled.lanes);setFlowNodes(reconciled.nodes);const currentById=new Map(flowNodes.map(node=>[node.id,node]));for(const node of reconciled.nodes){const current=currentById.get(node.id);if(!current||current.positionX!==node.positionX||current.positionY!==node.positionY||current.colorKey!==node.colorKey)await repository.updateNode(node);}setActiveLaneId(current=>reconciled.lanes.some(lane=>lane.id===current)?current:reconciled.lanes[0]?.id);setMessage(isCompact?"사용 흐름 소속을 유지하고 가로 간격을 좁혀 정렬했습니다.":isInterfaceProject(projectType)?"사용 시나리오별 화면·행동 정렬을 복원했습니다.":"입력과 처리 단계 중심의 기본 정렬을 복원했습니다.");}
  const selected=flowNodes.find(node=>node.id===selectedId);const selectedNextNodes=selected?flowEdges.filter(edge=>edge.sourceNodeId===selected.id).map(edge=>flowNodes.find(node=>node.id===edge.targetNodeId)).filter((node):node is UserFlowNode=>Boolean(node)):[];
  const isInterface=isInterfaceProject(projectType);
  return <section className="user-flow-page">
    <div className="user-flow-header"><div><p className="eyebrow">04 · {isInterface?"USER FLOW":"EXECUTION PIPELINE"}</p><h2>{isInterface?"사용자가 보는 화면 이동을 단계별로 펼칩니다.":"입력부터 결과까지 실행 단계를 펼칩니다."}</h2><p>{message}</p></div><div className="workflow-completion-summary" aria-label={`흐름 검수 완료 ${completionSummary.completed}/${completionSummary.total}`}><span>사용 흐름 검수</span><strong>{completionSummary.completed}/{completionSummary.total}개 · {completionSummary.percent}%</strong><progress aria-label="전체 사용 흐름 검수율" max={completionSummary.total||1} value={completionSummary.completed}/><div className="user-flow-view-actions"><button className={viewMode==="sheet"?"selected":""} onClick={()=>{setViewMode("sheet");setFocusNodeId(undefined);setActiveNodeId(undefined);setActiveLaneId(current=>current??lanes[0]?.id);setMessage("요구사항별 스윔레인을 왼쪽부터 탐색합니다.");}} type="button">대주제 시트</button><button className={viewMode==="overview"?"selected":""} onClick={()=>{setViewMode("overview");setFocusNodeId(undefined);setActiveNodeId(undefined);setMessage("전체 스윔레인을 한 화면에 표시합니다.");}} type="button">전체 보기</button>{viewMode==="focus"&&<span aria-current="true">연결 집중</span>}</div></div></div>
    {viewMode==="sheet"&&<nav aria-label={isInterface?"유저플로우 대주제 시트":"실행 파이프라인 대주제 시트"} className="user-flow-sheet-tabs">{lanes.map(lane=>{const summary=laneCompletion.get(lane.id);return <button aria-current={lane.id===activeLaneId?"page":undefined} className={lane.id===activeLaneId?"selected":""} key={lane.id} onClick={()=>{setActiveLaneId(lane.id);setActiveNodeId(undefined);setSelectedId(undefined);setMessage(`‘${lane.title}’ 스윔레인을 표시합니다.`);}} type="button"><span>{lane.title}</span><small>{summary?.completed??0}/{summary?.total??0}</small></button>;})}</nav>}
    <div className={`user-flow-canvas mode-${viewMode}`}><ReactFlow key={`${viewMode}-${activeLaneId??"all"}-${focusNodeId??"none"}`} nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodeDragStop={handleDragStop} onConnect={connection=>void handleConnect(connection)} fitView fitViewOptions={{nodes:viewMode==="focus"?contentNodes:laneNodes,padding:viewMode==="focus"?.14:.04,maxZoom:viewMode==="overview"?.72:1}} minZoom={.16} maxZoom={1.5} panOnScroll proOptions={{hideAttribution:true}}><Background color="var(--theme-border)" gap={28} size={1}/><Controls showInteractive/><Panel position="top-left"><span className="flow-view-status">{viewMode==="sheet"?`${visibleLanes[0]?.title??"대주제"} · ${contentNodes.length}개 단계`:viewMode==="focus"?`연결 집중 · ${contentNodes.length}개 단계`:`전체 보기 · ${flowNodes.length}개 단계`} · 검수 {visibleCompletionSummary.completed}/{visibleCompletionSummary.total}</span></Panel><Panel position="bottom-right"><div className="canvas-layout-controls"><button onClick={()=>void resetLayout(false)} type="button">자동 정렬</button><button onClick={()=>void resetLayout(true)} type="button">좁은 정렬</button></div></Panel></ReactFlow>{selected&&<FlowEditor key={selected.id} node={selected} lanes={lanes} nextNodes={selectedNextNodes} onSave={handleSave} onClose={()=>{setSelectedId(undefined);setActiveNodeId(undefined);}}/>}</div>
  </section>;
}
