import { useCallback, useEffect, useMemo, useState, type CSSProperties } from "react";
import { Background, Controls, MarkerType, MiniMap, ReactFlow, type Connection, type Edge, type Node } from "@xyflow/react";
import { createFeatureRepository } from "./adapters/featureRepository";
import { createUserFlowRepository } from "./adapters/userFlowRepository";
import { createDevelopmentFeatureSpec, NODE_COLORS } from "./domain/feature";
import { createUserFlowSpec, type UserFlowNode, type UserFlowNodeKind } from "./domain/userFlow";
import { UserFlowLaneNode, UserFlowNodeCard, type UserFlowNodeData } from "./UserFlowNodeCard";

const nodeTypes={userFlow:UserFlowNodeCard,userFlowLane:UserFlowLaneNode};
const FLOW_WORKSPACE_WIDTH=1920;const FLOW_WORKSPACE_HEIGHT=1080;
interface Props{projectId:string;sourceDocumentId:string;projectName?:string;}
function FlowEditor({node,onSave,onClose}:{node:UserFlowNode;onSave:(node:UserFlowNode)=>Promise<void>;onClose:()=>void}){
  const[draft,setDraft]=useState(node);const[message,setMessage]=useState<string>();
  async function save(){try{await onSave(draft);setMessage("유저플로우 단계를 저장했습니다.");}catch{setMessage("저장하지 못했습니다. 편집 내용은 유지됩니다.");}}
  async function changeColor(colorKey:UserFlowNode["colorKey"]){const updated={...draft,colorKey};setDraft(updated);setMessage("색상을 저장하는 중…");try{await onSave(updated);setMessage("노드 색상을 자동 저장했습니다.");}catch{setMessage("색상을 저장하지 못했습니다. 선택은 유지됩니다.");}}
  return <aside className="flow-editor"><button className="panel-close" onClick={onClose} type="button">×</button><div><p className="eyebrow">FLOW STEP DETAIL</p><h3>단계 편집</h3><small>ID {draft.id}</small><label>단계 이름<input aria-label="단계 이름" value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})}/></label><label>단계 종류<select aria-label="단계 종류" value={draft.kind} onChange={event=>setDraft({...draft,kind:event.target.value as UserFlowNodeKind})}><option value="phase">대단계</option><option value="screen">화면</option><option value="action">행동</option><option value="decision">분기</option><option value="result">결과</option></select></label><div className="node-color-palette" aria-label="노드 색상">{NODE_COLORS.map(color=><button aria-label={`${color.label} 색상`} className={draft.colorKey===color.key?"selected":""} key={color.key} onClick={()=>void changeColor(color.key)} style={{"--node-color":color.color} as CSSProperties} type="button" />)}</div><label>세부 내용<textarea aria-label="단계 세부 내용" rows={8} value={draft.description} onChange={event=>setDraft({...draft,description:event.target.value})}/></label><button onClick={()=>void save()} type="button">변경 저장</button>{message&&<p className="document-save-message">{message}</p>}</div></aside>;
}
export function UserFlowPage({projectId,sourceDocumentId,projectName}:Props){
  const featureRepository=useMemo(()=>createFeatureRepository(),[]);const repository=useMemo(()=>createUserFlowRepository(),[]);
  const generatedFeatures=useMemo(()=>createDevelopmentFeatureSpec(projectId,projectName),[projectId,projectName]);
  const[flowNodes,setFlowNodes]=useState<UserFlowNode[]>([]);const[flowEdges,setFlowEdges]=useState<import("./domain/userFlow").UserFlowEdge[]>([]);const[lanes,setLanes]=useState<import("./domain/userFlow").UserFlowLane[]>([]);const[selectedId,setSelectedId]=useState<string>();const[message,setMessage]=useState("유저플로우를 구성하는 중…");
  const[activeNodeId,setActiveNodeId]=useState<string>();
  useEffect(()=>{void featureRepository.initialize(projectId,sourceDocumentId,generatedFeatures).then(features=>{const generated=createUserFlowSpec(projectId,features);setLanes(generated.lanes);return repository.initialize(projectId,generated.nodes,generated.edges);}).then(spec=>{setFlowNodes(spec.nodes);setFlowEdges(spec.edges);setMessage("기능명세와 SQLite에서 유저플로우를 불러왔습니다.");}).catch(()=>setMessage("유저플로우를 불러오지 못했습니다."));},[featureRepository,generatedFeatures,projectId,repository,sourceDocumentId]);
  const visualLaneHeight=FLOW_WORKSPACE_HEIGHT/Math.max(1,lanes.length);
  const laneNodes:Node[] = lanes.map((lane,index)=>({id:`lane-${lane.id}`,type:"userFlowLane",position:{x:0,y:index*visualLaneHeight},data:{title:lane.title},draggable:false,selectable:false,connectable:false,zIndex:-1,style:{width:FLOW_WORKSPACE_WIDTH,height:visualLaneHeight}}));
  const contentNodes:Node<UserFlowNodeData>[] = flowNodes.map(node=>{const lane=lanes.find(item=>item.id===node.laneId);const scale=visualLaneHeight/(lane?.height??visualLaneHeight);return{id:node.id,type:"userFlow",selected:node.id===activeNodeId,parentId:`lane-${node.laneId}`,extent:"parent",position:{x:node.positionX,y:(node.positionY-(lane?.positionY??0))*scale},data:{node,onSelect:(item:UserFlowNode)=>setActiveNodeId(current=>current===item.id?undefined:item.id),onAdd:handleAddNode,onEdit:(item:UserFlowNode)=>setSelectedId(item.id),onDelete:handleDeleteNode},zIndex:2};});
  const nodes:Node[]=[...laneNodes,...contentNodes];
  const edges:Edge[]=flowEdges.map(edge=>({id:edge.id,source:edge.sourceNodeId,target:edge.targetNodeId,type:"smoothstep",markerEnd:{type:MarkerType.ArrowClosed},style:{strokeWidth:1.4}}));
  const handleDragStop=useCallback((_:MouseEvent|TouchEvent,node:Node)=>{const current=flowNodes.find(item=>item.id===node.id);if(!current)return;const lane=lanes.find(item=>item.id===current.laneId);const scale=visualLaneHeight/(lane?.height??visualLaneHeight);const updated={...current,positionX:node.position.x,positionY:node.position.y/scale+(lane?.positionY??0)};setFlowNodes(items=>items.map(item=>item.id===updated.id?updated:item));void repository.updateNode(updated).then(()=>setMessage("대주제 안에 단계 위치를 저장했습니다.")).catch(()=>setMessage("단계 위치를 저장하지 못했습니다."));},[flowNodes,lanes,repository,visualLaneHeight]);
  async function handleSave(node:UserFlowNode){const saved=await repository.updateNode(node);setFlowNodes(items=>items.map(item=>item.id===saved.id?saved:item));}
  async function handleConnect(connection:Connection){if(!connection.source||!connection.target)return;try{const edge=await repository.connect(projectId,connection.source,connection.target);setFlowEdges(items=>[...items,edge]);setMessage("단계 연결을 저장했습니다.");}catch(error){setMessage(error instanceof Error?error.message:"단계를 연결하지 못했습니다.");}}
  async function handleAddNode(parent:UserFlowNode){const node:UserFlowNode={id:`flow-${crypto.randomUUID()}`,projectId,laneId:parent.laneId,title:"새 단계",description:"이 단계의 사용자 행동과 완료 조건을 작성해 주세요.",kind:"action",positionX:parent.positionX+230,positionY:parent.positionY+58,colorKey:parent.colorKey??"violet"};try{const saved=await repository.createNode(node);const edge=await repository.connect(projectId,parent.id,saved.id);setFlowNodes(items=>[...items,saved]);setFlowEdges(items=>[...items,edge]);setActiveNodeId(saved.id);setSelectedId(saved.id);setMessage("같은 대주제에 다음 단계를 추가했습니다.");}catch(error){setMessage(error instanceof Error?error.message:"단계를 추가하지 못했습니다.");}}
  async function handleDeleteNode(node:UserFlowNode){if(!window.confirm(`‘${node.title}’ 단계와 연결선을 삭제할까요?`))return;try{await repository.deleteNode(projectId,node.id);setFlowNodes(items=>items.filter(item=>item.id!==node.id));setFlowEdges(items=>items.filter(edge=>edge.sourceNodeId!==node.id&&edge.targetNodeId!==node.id));setActiveNodeId(undefined);setSelectedId(undefined);setMessage("단계와 연결선을 삭제했습니다.");}catch(error){setMessage(error instanceof Error?error.message:"단계를 삭제하지 못했습니다.");}}
  async function resetLayout(){const features=await featureRepository.initialize(projectId,sourceDocumentId,generatedFeatures);const generated=createUserFlowSpec(projectId,features);setLanes(generated.lanes);setFlowNodes(current=>current.map(node=>{const base=generated.nodes.find(item=>item.id===node.id);if(!base)return node;void repository.updateNode({...node,positionX:base.positionX,positionY:base.positionY});return {...node,positionX:base.positionX,positionY:base.positionY};}));setMessage("첨부 화면형 기본 정렬을 복원했습니다.");}
  const selected=flowNodes.find(node=>node.id===selectedId);
  return <section className="user-flow-page"><div className="user-flow-header"><div><p className="eyebrow">04 · USER FLOW</p><h2>기능 흐름을 단계별로 펼칩니다.</h2><p>{message}</p></div><div><button className="secondary" onClick={()=>void resetLayout()} type="button">기본 정렬</button></div></div><div className="user-flow-canvas"><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodeDragStop={handleDragStop} onConnect={connection=>void handleConnect(connection)} fitView fitViewOptions={{nodes:laneNodes,padding:.02,maxZoom:1}} minZoom={.18} maxZoom={1.5} panOnScroll><Background color="var(--theme-border)" gap={28} size={1}/><MiniMap pannable zoomable/><Controls showInteractive={false}/></ReactFlow>{selected&&<FlowEditor key={selected.id} node={selected} onSave={handleSave} onClose={()=>setSelectedId(undefined)}/>}</div></section>;
}
