import { useCallback, useEffect, useMemo, useState, type CSSProperties } from "react";
import { Background, Controls, MarkerType, Panel, ReactFlow, type Connection, type Edge, type Node } from "@xyflow/react";
import { createFeatureRepository } from "./adapters/featureRepository";
import { createUserFlowRepository } from "./adapters/userFlowRepository";
import { createDevelopmentFeatureSpec, NODE_COLORS } from "./domain/feature";
import { connectedUserFlowNodeIds, createUserFlowSpec, type UserFlowNode, type UserFlowNodeKind } from "./domain/userFlow";
import { UserFlowLaneNode, UserFlowNodeCard, type UserFlowNodeData } from "./UserFlowNodeCard";

const nodeTypes={userFlow:UserFlowNodeCard,userFlowLane:UserFlowLaneNode};
const FLOW_WORKSPACE_HEIGHT=1080;const SHEET_LANE_HEIGHT=680;const OVERVIEW_LANE_HEIGHT=170;const USER_FLOW_LAYOUT_VERSION="visible-screen-journey-v7";
type UserFlowViewMode="sheet"|"overview"|"focus";
interface Props{projectId:string;sourceDocumentId:string;projectName?:string;projectIdea?:string;}
function FlowEditor({node,onSave,onClose}:{node:UserFlowNode;onSave:(node:UserFlowNode)=>Promise<void>;onClose:()=>void}){
  const[draft,setDraft]=useState(node);const[message,setMessage]=useState<string>();
  async function save(){try{await onSave(draft);setMessage("유저플로우 단계를 저장했습니다.");}catch{setMessage("저장하지 못했습니다. 편집 내용은 유지됩니다.");}}
  async function changeColor(colorKey:UserFlowNode["colorKey"]){const updated={...draft,colorKey};setDraft(updated);setMessage("색상을 저장하는 중…");try{await onSave(updated);setMessage("노드 색상을 자동 저장했습니다.");}catch{setMessage("색상을 저장하지 못했습니다. 선택은 유지됩니다.");}}
  return <aside className="flow-editor"><button className="panel-close" onClick={onClose} type="button">×</button><div><p className="eyebrow">FLOW STEP DETAIL</p><h3>단계 편집</h3><small>ID {draft.id}</small><label>단계 이름<input aria-label="단계 이름" value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})}/></label><label>단계 종류<select aria-label="단계 종류" value={draft.kind} onChange={event=>setDraft({...draft,kind:event.target.value as UserFlowNodeKind})}><option value="phase">대단계</option><option value="screen">화면</option><option value="action">행동</option><option value="decision">분기</option><option value="result">결과</option></select></label><div className="node-color-palette" aria-label="노드 색상">{NODE_COLORS.map(color=><button aria-label={`${color.label} 색상`} className={draft.colorKey===color.key?"selected":""} key={color.key} onClick={()=>void changeColor(color.key)} style={{"--node-color":color.color} as CSSProperties} type="button" />)}</div><label>세부 내용<textarea aria-label="단계 세부 내용" rows={8} value={draft.description} onChange={event=>setDraft({...draft,description:event.target.value})}/></label><button onClick={()=>void save()} type="button">변경 저장</button>{message&&<p className="document-save-message">{message}</p>}</div></aside>;
}
export function UserFlowPage({projectId,sourceDocumentId,projectName,projectIdea}:Props){
  const featureRepository=useMemo(()=>createFeatureRepository(),[]);const repository=useMemo(()=>createUserFlowRepository(),[]);
  const generatedFeatures=useMemo(()=>createDevelopmentFeatureSpec(projectId,projectName,projectIdea),[projectId,projectName,projectIdea]);
  const[flowNodes,setFlowNodes]=useState<UserFlowNode[]>([]);const[flowEdges,setFlowEdges]=useState<import("./domain/userFlow").UserFlowEdge[]>([]);const[lanes,setLanes]=useState<import("./domain/userFlow").UserFlowLane[]>([]);const[selectedId,setSelectedId]=useState<string>();const[message,setMessage]=useState("유저플로우를 구성하는 중…");
  const[activeNodeId,setActiveNodeId]=useState<string>();const[focusNodeId,setFocusNodeId]=useState<string>();const[viewMode,setViewMode]=useState<UserFlowViewMode>("sheet");const[activeLaneId,setActiveLaneId]=useState<string>();
  useEffect(()=>{const versionKey=`projectstudio:${projectId}:user-flow-layout`;const shouldReplace=localStorage.getItem(versionKey)!==USER_FLOW_LAYOUT_VERSION;void featureRepository.initialize(projectId,sourceDocumentId,generatedFeatures).then(features=>{const generated=createUserFlowSpec(projectId,features);setLanes(generated.lanes);setActiveLaneId(generated.lanes[0]?.id);return repository.initialize(projectId,generated.nodes,generated.edges,shouldReplace);}).then(spec=>{setFlowNodes(spec.nodes);setFlowEdges(spec.edges);if(shouldReplace)localStorage.setItem(versionKey,USER_FLOW_LAYOUT_VERSION);setMessage(shouldReplace?"실제 화면과 사용자 행동 중심의 가로 흐름으로 다시 구성했습니다.":"대주제별 유저플로우 시트를 불러왔습니다.");}).catch(()=>setMessage("유저플로우를 불러오지 못했습니다."));},[featureRepository,generatedFeatures,projectId,repository,sourceDocumentId]);
  const focusedIds=useMemo(()=>viewMode==="focus"&&focusNodeId?connectedUserFlowNodeIds(flowEdges,focusNodeId,2):undefined,[flowEdges,focusNodeId,viewMode]);
  const visibleFlowNodes=focusedIds?flowNodes.filter(node=>focusedIds.has(node.id)):viewMode==="sheet"?flowNodes.filter(node=>node.laneId===activeLaneId):flowNodes;const visibleLaneIds=new Set(visibleFlowNodes.map(node=>node.laneId));const visibleLanes=viewMode==="overview"?lanes:lanes.filter(lane=>visibleLaneIds.has(lane.id));
  const visualLaneHeight=viewMode==="overview"?OVERVIEW_LANE_HEIGHT:viewMode==="sheet"?SHEET_LANE_HEIGHT:Math.min(360,FLOW_WORKSPACE_HEIGHT);
  const workspaceWidth=Math.max(viewMode==="overview"?1920:1280,...visibleFlowNodes.map(node=>node.positionX+420));const laneNodes:Node[] = visibleLanes.map((lane,index)=>({id:`lane-${lane.id}`,type:"userFlowLane",position:{x:0,y:index*visualLaneHeight},data:{title:viewMode==="sheet"?"":lane.title,colorKey:lane.colorKey},draggable:false,selectable:false,connectable:false,zIndex:-1,style:{width:workspaceWidth,height:visualLaneHeight}}));
  const contentNodes:Node<UserFlowNodeData>[] = visibleFlowNodes.map(node=>{const lane=lanes.find(item=>item.id===node.laneId);const scale=visualLaneHeight/(lane?.height??visualLaneHeight);const overviewOffset=viewMode==="overview"?170:40;return{id:node.id,type:"userFlow",selected:node.id===activeNodeId,parentId:`lane-${node.laneId}`,extent:"parent",position:{x:node.positionX+overviewOffset,y:(node.positionY-(lane?.positionY??0))*scale},data:{node,onSelect:(item:UserFlowNode)=>{setActiveNodeId(item.id);setFocusNodeId(item.id);setViewMode("focus");setMessage(`‘${item.title}’ 전후 2단계에 집중해서 표시합니다.`);},onAdd:handleAddNode,onEdit:(item:UserFlowNode)=>setSelectedId(item.id),onDelete:handleDeleteNode},zIndex:2,className:viewMode==="overview"?"overview-node":""};});
  const nodes:Node[]=[...laneNodes,...contentNodes];const visibleNodeIds=new Set(visibleFlowNodes.map(node=>node.id));
  const edges:Edge[]=flowEdges.filter(edge=>visibleNodeIds.has(edge.sourceNodeId)&&visibleNodeIds.has(edge.targetNodeId)).map(edge=>({id:edge.id,source:edge.sourceNodeId,target:edge.targetNodeId,type:"smoothstep",pathOptions:{borderRadius:10,offset:28},markerEnd:{type:MarkerType.ArrowClosed,color:"var(--theme-connector)"},style:{stroke:"var(--theme-connector)",strokeWidth:2}}));
  const handleDragStop=useCallback((_:MouseEvent|TouchEvent,node:Node)=>{const current=flowNodes.find(item=>item.id===node.id);if(!current)return;const lane=lanes.find(item=>item.id===current.laneId);const scale=visualLaneHeight/(lane?.height??visualLaneHeight);const updated={...current,positionX:node.position.x,positionY:node.position.y/scale+(lane?.positionY??0)};setFlowNodes(items=>items.map(item=>item.id===updated.id?updated:item));void repository.updateNode(updated).then(()=>setMessage("대주제 안에 단계 위치를 저장했습니다.")).catch(()=>setMessage("단계 위치를 저장하지 못했습니다."));},[flowNodes,lanes,repository,visualLaneHeight]);
  async function handleSave(node:UserFlowNode){const saved=await repository.updateNode(node);setFlowNodes(items=>items.map(item=>item.id===saved.id?saved:item));}
  async function handleConnect(connection:Connection){if(!connection.source||!connection.target)return;try{const edge=await repository.connect(projectId,connection.source,connection.target);setFlowEdges(items=>[...items,edge]);setMessage("단계 연결을 저장했습니다.");}catch(error){setMessage(error instanceof Error?error.message:"단계를 연결하지 못했습니다.");}}
  async function handleAddNode(parent:UserFlowNode){const node:UserFlowNode={id:`flow-${crypto.randomUUID()}`,projectId,laneId:parent.laneId,title:"새 단계",description:"이 단계의 사용자 행동과 완료 조건을 작성해 주세요.",kind:"action",positionX:parent.positionX+230,positionY:parent.positionY+58,colorKey:parent.colorKey??"violet"};try{const saved=await repository.createNode(node);const edge=await repository.connect(projectId,parent.id,saved.id);setFlowNodes(items=>[...items,saved]);setFlowEdges(items=>[...items,edge]);setActiveNodeId(saved.id);setSelectedId(saved.id);setMessage("같은 대주제에 다음 단계를 추가했습니다.");}catch(error){setMessage(error instanceof Error?error.message:"단계를 추가하지 못했습니다.");}}
  async function handleDeleteNode(node:UserFlowNode){if(!window.confirm(`‘${node.title}’ 단계와 연결선을 삭제할까요?`))return;try{await repository.deleteNode(projectId,node.id);setFlowNodes(items=>items.filter(item=>item.id!==node.id));setFlowEdges(items=>items.filter(edge=>edge.sourceNodeId!==node.id&&edge.targetNodeId!==node.id));setActiveNodeId(undefined);setSelectedId(undefined);setMessage("단계와 연결선을 삭제했습니다.");}catch(error){setMessage(error instanceof Error?error.message:"단계를 삭제하지 못했습니다.");}}
  async function resetLayout(isCompact=false){const features=await featureRepository.initialize(projectId,sourceDocumentId,generatedFeatures);const generated=createUserFlowSpec(projectId,features);setLanes(generated.lanes);setFlowNodes(current=>current.map(node=>{const base=generated.nodes.find(item=>item.id===node.id);if(!base)return node;const updated={...node,positionX:isCompact?80+(base.positionX-90)*.84:base.positionX,positionY:base.positionY,colorKey:base.colorKey};void repository.updateNode(updated);return updated;}));setMessage(isCompact?"가로 간격을 좁혀 정렬했습니다.":"화면과 사용자 행동 중심의 기본 정렬을 복원했습니다.");}
  const selected=flowNodes.find(node=>node.id===selectedId);
  return <section className="user-flow-page"><div className="user-flow-header"><div><p className="eyebrow">04 · USER FLOW</p><h2>기능 흐름을 단계별로 펼칩니다.</h2><p>{message}</p></div><div className="user-flow-view-actions"><button className={viewMode==="sheet"?"selected":""} onClick={()=>{setViewMode("sheet");setFocusNodeId(undefined);setActiveNodeId(undefined);setActiveLaneId(current=>current??lanes[0]?.id);setMessage("대주제별 시트에서 첫 단계부터 가로로 탐색합니다.");}} type="button">대주제 시트</button><button className={viewMode==="overview"?"selected":""} onClick={()=>{setViewMode("overview");setFocusNodeId(undefined);setActiveNodeId(undefined);setMessage("전체 흐름을 축소 지도 형태로 표시합니다.");}} type="button">전체 지도</button>{viewMode==="focus"&&<span aria-current="true">연결 집중</span>}</div></div>{viewMode==="sheet"&&<nav aria-label="유저플로우 대주제 시트" className="user-flow-sheet-tabs">{lanes.map(lane=><button aria-current={lane.id===activeLaneId?"page":undefined} className={lane.id===activeLaneId?"selected":""} key={lane.id} onClick={()=>{setActiveLaneId(lane.id);setActiveNodeId(undefined);setMessage(`‘${lane.title}’ 대주제 시트를 표시합니다.`);}} type="button">{lane.title}</button>)}</nav>}<div className={`user-flow-canvas mode-${viewMode}`}><ReactFlow key={`${viewMode}-${activeLaneId??"all"}-${focusNodeId??"none"}`} nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodeDragStop={handleDragStop} onConnect={connection=>void handleConnect(connection)} defaultViewport={{x:0,y:60,zoom:.82}} fitView={viewMode!=="sheet"} fitViewOptions={{nodes:viewMode==="focus"?contentNodes:laneNodes,padding:viewMode==="focus"?.14:.02,maxZoom:viewMode==="focus"?1.15:1}} minZoom={.18} maxZoom={1.5} panOnScroll proOptions={{hideAttribution:true}}><Background color="var(--theme-border)" gap={28} size={1}/><Controls showInteractive={false}/><Panel position="top-left"><span className="flow-view-status">{viewMode==="sheet"?`${visibleLanes[0]?.title??"대주제"} · ${contentNodes.length}개 단계`:viewMode==="focus"?`연결 집중 · ${contentNodes.length}개 단계`:`전체 지도 · ${flowNodes.length}개 단계`}</span></Panel><Panel position="bottom-right"><div className="canvas-layout-controls"><button onClick={()=>void resetLayout(false)} type="button">기본 정렬</button><button onClick={()=>void resetLayout(true)} type="button">좁은 정렬</button></div></Panel></ReactFlow>{selected&&<FlowEditor key={selected.id} node={selected} onSave={handleSave} onClose={()=>setSelectedId(undefined)}/>}</div></section>;
}
